##
# Spring and DataSource
##
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

##
# Spring Security - OAuth2 Resource Server
##
  security:
     oauth2:
       resourceserver:
         jwt:
          issuer-uri: http://localhost:18080/realms/nosa-loja-virtual

management:
  endpoints:
    web:
      exposure:
        include: info, configprops, health
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: 'true'



#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#      SQL: debug

